### ISSUE TITLE
linecounter doesn't count the number of lines

### ISSUE THREAD

**Issue by MareoRaft** [halitkarakis/line-counter#4]
Observe

    ~/Desktop/test % linecounter -fd new.txt
    total lines: 0

but the contents of the file are

    hello
    bye
    other

which is more than 0 lines.

**Comment by mhalitk** [comment]
Thank you for reporting. It seems help text is not open and usage information is not declaring that you should use either -f or -d option.

Your usage is wrong, you should use -f option to specify that you will give file path to count lines, -d option stands for giving directory path to count lines.

You should use as below to make your case work

`
linecounter -f new.txt
`

**Comment by MareoRaft** [comment]
Thank you for your response!  That usage gives me:

    % linecounter -f itcont.txt
    Traceback (most recent call last):
      File "/usr/local/bin/linecounter", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python2.7/site-packages/linecounter.py", line 137, in main
        total_line = line_count_files(paths, flags)
      File "/usr/local/lib/python2.7/site-packages/linecounter.py", line 66, in line_count_files
        current = line_count_file(file_name, flags)
      File "/usr/local/lib/python2.7/site-packages/linecounter.py", line 51, in line_count_file
        with open(file_path, encoding="ascii", errors="surrogateescape") as current_file:
    TypeError: 'errors' is an invalid keyword argument for this function
